export const contactNumber = "03125770904";
export const siteTitle = "Office of Research, Innovation and Commercialization";
export const aboutOric = [
  {
    id: 1,
    name: "Dr. Muhammad Latif Gondal",
    designation: "Executive Director (P & M)",
    phone: "051-9057255, 051-9250165",
    email: "muhammad.latif@aiou.edu.pk",
  },
  {
    id: 2,
    name: "Dr. Saima Nasir",
    designation: "Additional Director Research",
    phone: "051-9057725",
    email: "saima.nasir@aiou.edu.pk",
  },
  {
    id: 3,
    name: "Mrs. Jamila Ahmed",
    designation: "Senior Research Officer",
    phone: "051-9057419",
    email: "jamila.ahmed@aiou.edu.pk",
  },
  {
    id: 4,
    name: "Mr. Muhammad Mushtaq",
    designation: "Manager Research Operations",
    phone: "051-9057605",
    email: "muhammad.mushtaq@aiou.edu.pk",
  },
  {
    id: 5,
    name: "Mr. Talha Saeed Satti",
    designation: "Research Associate",
    phone: "051-9057419",
    email: "talha.saeed@aiou.edu.pk",
  },
  {
    id: 6,
    name: "Mr. Shafique Ahmed",
    designation: "Personal Assistant",
    phone: "051-9057424",
    email: "shafique.ahmed@aiou.edu.pk",
  },
  {
    id: 7,
    name: "Ms. Nabila Khurshid",
    designation: "Research Assistant",
    phone: "051-9057420",
    email: "nabila.khurshid@aiou.edu.pk",
  },
  {
    id: 8,
    name: "Ms. Kanwal Fatima",
    designation: "Assistant Editor (English)",
    phone: "051-9057420",
    email: "kanwal.fatima@aiou.edu.pk",
  },
  {
    id: 9,
    name: "Mr. Awais Ashraf",
    designation: "Research Assistant",
    phone: "051-9057423",
    email: "awais.ashraf@aiou.edu.pk",
  },
  {
    id: 10,
    name: "Ms. Ayesha",
    designation: "Research Assistant",
    phone: "051-9057420",
    email: "ayesha.zahid@aiou.edu.pk",
  },
  {
    id: 11,
    name: "Mr. Asad Ullah Qureshi",
    designation: "Lower Division Clerk",
    phone: "051-9057424",
    email: "asad.qureshi@aiou.edu.pk",
  },
  {
    id: 12,
    name: "Mr. Khurram Shehzad",
    designation: "Lower Division Clerk",
    phone: "051-9057605",
    email: "*********@aiou.edu.pk",
  },
  {
    id: 13,
    name: "Mr. Naeem Ullah Mumtaz",
    designation: "Naib Qasid",
    phone: "051-*******",
    email: "*********@aiou.edu.pk",
  },
  {
    id: 14,
    name: "Mr. Asad Mehmood",
    designation: "Naib Qasid",
    phone: "051-*******",
    email: "*********@aiou.edu.pk",
  },
];
