export const years = [
  { value: "2024", label: "2024" },
  { value: "2023", label: "2023" },
  { value: "2022", label: "2022" },
  { value: "2021", label: "2021" },
  { value: "2020", label: "2020" },
  { value: "2019", label: "2019" },
  { value: "2018", label: "2018" },
  { value: "2017", label: "2017" },
  { value: "2016", label: "2016" },
  { value: "2015", label: "2015" },
  { value: "2014", label: "2014" },
  { value: "2013", label: "2013" },
  { value: "2012", label: "2012" },
  { value: "2011", label: "2011" },
  { value: "2010", label: "2010" },
  { value: "2009", label: "2009" },
  { value: "2008", label: "2008" },
  { value: "2007", label: "2007" },
  { value: "2006", label: "2006" },
  { value: "2005", label: "2005" },
  { value: "2004", label: "2004" },
  { value: "2003", label: "2003" },
  { value: "2002", label: "2002" },
  { value: "2001", label: "2001" },
  { value: "2000", label: "2000" },
  { value: "1999", label: "1999" },
  { value: "1998", label: "1998" },
  { value: "1997", label: "1997" },
  { value: "1996", label: "1996" },
  { value: "1995", label: "1995" },
  { value: "1994", label: "1994" },
  { value: "1993", label: "1993" },
  { value: "1992", label: "1992" },
  { value: "1991", label: "1991" },
  { value: "1990", label: "1990" },
  { value: "1989", label: "1989" },
  { value: "1988", label: "1988" },
  { value: "1987", label: "1987" },
  { value: "1986", label: "1986" },
  { value: "1985", label: "1985" },
  { value: "1984", label: "1984" },
  { value: "1983", label: "1983" },
  { value: "1982", label: "1982" },
  { value: "1981", label: "1981" },
  { value: "1980", label: "1980" },
  { value: "1979", label: "1979" },
  { value: "1978", label: "1978" },
  { value: "1977", label: "1977" },
  { value: "1976", label: "1976" },
  { value: "1975", label: "1975" },
  { value: "1974", label: "1974" },
  { value: "1973", label: "1973" },
  { value: "1972", label: "1972" },
  { value: "1971", label: "1971" },
  { value: "1970", label: "1970" },
  { value: "1969", label: "1969" },
  { value: "1968", label: "1968" },
  { value: "1967", label: "1967" },
  { value: "1966", label: "1966" },
  { value: "1965", label: "1965" },
  { value: "1964", label: "1964" },
  { value: "1963", label: "1963" },
  { value: "1962", label: "1962" },
  { value: "1961", label: "1961" },
  { value: "1960", label: "1960" },
  { value: "1959", label: "1959" },
  { value: "1958", label: "1958" },
  { value: "1957", label: "1957" },
  { value: "1956", label: "1956" },
  { value: "1955", label: "1955" },
  { value: "1954", label: "1954" },
  { value: "1953", label: "1953" },
  { value: "1952", label: "1952" },
  { value: "1951", label: "1951" },
  { value: "1950", label: "1950" },
];

export const numbers = [
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 3 },
  { value: 4 },
  { value: 5 },
  { value: 6 },
  { value: 7 },
  { value: 8 },
  { value: 9 },
  { value: 10 },
  { value: 11 },
  { value: 12 },
  { value: 13 },
  { value: 14 },
  { value: 15 },
  { value: 16 },
  { value: 17 },
  { value: 18 },
  { value: 19 },
  { value: 20 },
  { value: 21 },
  { value: 22 },
  { value: 23 },
  { value: 24 },
  { value: 25 },
  { value: 26 },
  { value: 27 },
  { value: 28 },
  { value: 29 },
  { value: 30 },
  { value: 31 },
  { value: 32 },
  { value: 33 },
  { value: 34 },
  { value: 35 },
  { value: 36 },
  { value: 37 },
  { value: 38 },
  { value: 39 },
  { value: 40 },
  { value: 41 },
  { value: 42 },
  { value: 43 },
  { value: 44 },
  { value: 45 },
  { value: 46 },
  { value: 47 },
  { value: 48 },
  { value: 49 },
  { value: 50 },
];

//Form Titles
export const formTitles = [
  "1. Research Publications (Impact Journal / HJRS / HEC Recognized Journals)",
  "2. Book Authored / Edited",
  "3. Research Projects",
  "4. Trainings / Workshops / Seminars / Conferences",
  "5. Thesis / FYP Supervised",
  "6. Policy Advocacy or Case Studies Presented to Government Department",
  "7. Links Established with other HEIs / Corporate Sector / Industry / Community",
  "8. Contract Research Awarded by Industry or Government Organizations",
  "9. Civic Engagement Events / Initiatives on Issues of Public Concern",
  "10. Consultancy Contracts with Industry, Commerce or Government",
  "11. Patents / Trade Marks / Design Patent / Copyrights, etc.",
  "12. Research Products / Process / Prototype (e.g. Architectural designs, Assesment tools, Books, Softwares, Apps, Video Lectures, Arts designs,  etc)",
  "13. Science / Arts Products or any Creative Activity / Exhibitions / Showcasing Events / Industry Linkages / Book Fair Arranged by your Department",
  "14. Agreements Signed for Collaboration with Industry, Government or Community (at National / International Level)",
  "15. National or International Honors or Awards Won",
  "16. Do you provide data to HEC, NGOs or any other organization?",
  "17. Community Work",
  "18. Mentorship Programmes",
  "19. Student Organizations / Associations / Clubs / Alumni Groups",
];

// FACULTIES
export const faculties = [
  {
    id: 1,
    title: "Faculty of Arabic and Islamic Studies",
    href: "faculty-of-arabic-and-social-studies",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    departments: [
      {
        id: 1,
        title: "QURAN AND TAFSEER",
        href: "quran-and-tafseer",
      },
      {
        id: 2,
        title: "ARABIC LANGUAGE & LITERATURE",
        href: "arabic-language-literature",
      },
      {
        id: 3,
        title: "SHARI'AH (ISLAMIC LAW & JURISPRUDENCE)",
        href: "shariah",
      },
      {
        id: 4,
        title: "ISLAMIC THOUGHT, HISTORY AND CULTURE",
        href: "islamic-thought",
      },
      {
        id: 5,
        title: "INTERFAITH STUDIES",
        href: "interfaith-studies",
      },
      {
        id: 6,
        title: "HADITH & HADITH SCIENCES",
        href: "hadith-sciences",
      },
      {
        id: 7,
        title: "SEERAT STUDIES",
        href: "seerat-studies",
      },
    ],
  },
  {
    id: 2,
    title: "Faculty of Education",
    href: "faculty-of-education",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    departments: [
      {
        id: 1,
        title: "EDUCATIONAL PLANNING, POLICY STUDIES AND LEADERSHIP (EPPSL)",
        href: "educational-planning",
      },
      {
        id: 2,
        title: "DISTANCE, NON-FORMAL AND CONTINUING EDUCATION",
        href: "non-formal-and-continuing-education",
      },
      {
        id: 3,
        title: "EARLY CHILDHOOD EDUCATION & ELEMENTARY TEACHER EDUCATION",
        href: "early-childhood-education",
      },
      {
        id: 4,
        title: "SCIENCE EDUCATION",
        href: "science-education",
      },
      {
        id: 5,
        title: "SPECIAL EDUCATION",
        href: "special-education",
      },
      {
        id: 6,
        title: "SECONDARY TEACHER EDUCATION",
        href: "secondary-teacher-education",
      },
      {
        id: 7,
        title: "Center for Social Reconstruction",
        href: "center-for-social-reconstruction",
      },
    ],
  },
  {
    id: 3,
    title: "Faculty of Sciences",
    href: "faculty-of-sciences",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    departments: [
      {
        id: 1,
        title: "CHEMISTRY",
        href: "chemistry",
      },
      {
        id: 2,
        title: "BIOLOGY",
        href: "biology",
      },
      {
        id: 3,
        title: "MATHEMATICS",
        href: "mathematics",
      },
      {
        id: 4,
        title: "COMPUTER SCIENCE",
        href: "computer-science",
      },
      {
        id: 5,
        title: "PHYSICS",
        href: "physics",
      },
      {
        id: 6,
        title: "AGRICULTURAL SCIENCES",
        href: "agricultural-sciences",
      },
      {
        id: 7,
        title: "STATISTICS",
        href: "statistics",
      },
      {
        id: 8,
        title: "ENVIRONMENTAL SCIENCES",
        href: "environmental-sciences",
      },
      {
        id: 9,
        title: "ENGINEERING AND TECHNOLOGY",
        href: "engineering-and-technology",
      },
      {
        id: 10,
        title: "NUTRITIONAL SCIENCES & ENVIRONMENTAL DESIGN",
        href: "nutritional-sciences-and-environmental-design",
      },
    ],
  },
  {
    id: 4,
    title: "Faculty of Social Sciences and Humanities",
    href: "faculty-of-social-sciences-and-humanities",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    departments: [
      {
        id: 1,
        title: "URDU",
        href: "urdu",
      },
      {
        id: 2,
        title: "COMMERCE",
        href: "commerce",
      },
      {
        id: 3,
        title: "IQBAL STUDIES",
        href: "iqbal-studies",
      },
      {
        id: 4,
        title: "MASS COMMUNICATION",
        href: "mass-communication",
      },
      {
        id: 5,
        title: "LIBRARY AND INFORMATION SCIENCE",
        href: "library-and-information-science",
      },
      {
        id: 6,
        title: "GENDER AND WOMEN STUDIES",
        href: "gender-and-women-studies",
      },
      {
        id: 7,
        title: "PAKISTANI LANGUAGE",
        href: "pakistani-language",
      },
      {
        id: 8,
        title: "ENGLISH",
        href: "english",
      },
      {
        id: 9,
        title: "BUSINESS ADMINISTRATION",
        href: "business-administration",
      },
      {
        id: 10,
        title: "SOCIOLOGY, SOCIAL WORK & POP. STUDIES",
        href: "social-work-and-pop-studies",
      },
      {
        id: 11,
        title: "ECONOMICS",
        href: "economics",
      },
      {
        id: 12,
        title: "FRENCH",
        href: "french",
      },
      {
        id: 13,
        title: "HISTORY",
        href: "history",
      },
      {
        id: 14,
        title: "PAKISTAN STUDIES",
        href: "pakistan-studies",
      },
    ],
  },
];

// NAVLINKS
export const navLinks = [
  { id: 1, title: "Home", href: "/" },
  { id: 2, title: "About ORIC", href: "/about" },
  { id: 3, title: "Contact", href: "/contact" },
];

export const nameTitles = [
  { title: "Dr" },
  { title: "Mr" },
  { title: "Ms" },
  { title: "Mrs" },
];
