export const years = [
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "1999",
  "1998",
  "1997",
  "1996",
  "1995",
  "1994",
  "1993",
  "1992",
  "1991",
  "1990",
  "1989",
  "1988",
  "1987",
  "1986",
  "1985",
  "1984",
  "1983",
  "1982",
  "1981",
  "1980",
  "1979",
  "1978",
  "1977",
  "1976",
  "1975",
  "1974",
  "1973",
  "1972",
  "1971",
  "1970",
  "1969",
  "1968",
  "1967",
  "1966",
  "1965",
  "1964",
  "1963",
  "1962",
  "1961",
  "1960",
  "1959",
  "1958",
  "1957",
  "1956",
  "1955",
  "1954",
  "1953",
  "1952",
  "1951",
  "1950",
];

// All countries
export const countries = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, Democratic Republic of the Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D'Ivoire",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, the Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Serbia and Montenegro",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "St Martin",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.s.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const SDG = [
  "SDG 1 - No poverty",
  "SDG 2 - Zero hunger",
  "SDG 3 - Good health and well-being",
  "SDG 4 - Quality education",
  "SDG 5 - Gender equality",
  "SDG 6 - Clean water and sanitation",
  "SDG 7 - Affordable and clean energy",
  "SDG 8 - Decent work and economic growth",
  "SDG 9 - Industry, innovation and infrastructure",
  "SDG 10 - Reduced inequalities",
  "SDG 11 - Sustainable cities and communities",
  "SDG 12 - Responsible consumption and production",
  "SDG 13 - Climate action",
  "SDG 14 - Life below water",
  "SDG 15 - Life on land",
  "SDG 16 - Peace, justice and strong institutions",
  "SDG 17 - Partnerships for the goals",
];

export const numbers = [
  { value: 0 },
  { value: 1 },
  { value: 2 },
  { value: 3 },
  { value: 4 },
  { value: 5 },
  { value: 6 },
  { value: 7 },
  { value: 8 },
  { value: 9 },
  { value: 10 },
  { value: 11 },
  { value: 12 },
  { value: 13 },
  { value: 14 },
  { value: 15 },
  { value: 16 },
  { value: 17 },
  { value: 18 },
  { value: 19 },
  { value: 20 },
  { value: 21 },
  { value: 22 },
  { value: 23 },
  { value: 24 },
  { value: 25 },
  { value: 26 },
  { value: 27 },
  { value: 28 },
  { value: 29 },
  { value: 30 },
  { value: 31 },
  { value: 32 },
  { value: 33 },
  { value: 34 },
  { value: 35 },
  { value: 36 },
  { value: 37 },
  { value: 38 },
  { value: 39 },
  { value: 40 },
  { value: 41 },
  { value: 42 },
  { value: 43 },
  { value: 44 },
  { value: 45 },
  { value: 46 },
  { value: 47 },
  { value: 48 },
  { value: 49 },
  { value: 50 },
];

export const formHead1 = [
  {
    id: 1,
    name: "Sr. No",
  },
  {
    id: 2,
    name: "Year",
  },
  {
    id: 3,
    name: "Journal Name",
  },
  {
    id: 4,
    name: "Title of Research Paper",
  },
  {
    id: 5,
    name: "Authors",
  },
  {
    id: 6,
    name: "Category",
  },
  {
    id: 7,
    name: "Status",
  },
  {
    id: 8,
    name: "ISSN",
  },
  {
    id: 9,
    name: "Volume",
  },
  {
    id: 10,
    name: "Page No(s)",
  },
  {
    id: 11,
    name: "Affiliation with AIOU",
  },
  {
    id: 12,
    name: "Web Link",
  },
  {
    id: 13,
    name: "Affiliation of authors",
  },
  {
    id: 14,
    name: "Addressing any SGD",
  },
];

export const formHead2 = [
  {
    id: 1,
    name: "Sr. No",
  },
  {
    id: 2,
    name: "Year",
  },
  {
    id: 3,
    name: "Book Title",
  },
  {
    id: 4,
    name: "Research Title",
  },
  {
    id: 5,
    name: "Publisher",
  },
  {
    id: 6,
    name: "Role",
  },
  {
    id: 7,
    name: "Country",
  },
  {
    id: 8,
    name: "ISBN",
  },
  {
    id: 9,
    name: "Web Link",
  },
  {
    id: 10,
    name: "Page(s)",
  },
  {
    id: 11,
    name: "Affiliation with AIOU",
  },
  {
    id: 12,
    name: "Addressing any SGD",
  },
];

export const formHead3 = [
  {
    id: 1,
    name: "Sr. No",
  },
  {
    id: 2,
    name: "Year",
  },
  {
    id: 3,
    name: "Funding Agency",
  },
  {
    id: 4,
    name: "Research Name",
  },
  {
    id: 5,
    name: "Status",
  },
  {
    id: 6,
    name: "Type",
  },
  {
    id: 7,
    name: "Role",
  },
  {
    id: 8,
    name: "Grant Amount",
  },
  {
    id: 9,
    name: "Title",
  },
  {
    id: 10,
    name: "Start Date",
  },
  {
    id: 11,
    name: "End Date",
  },
  {
    id: 12,
    name: "Total Funding",
  },
  {
    id: 13,
    name: "Collaborating Partner",
  },
  {
    id: 14,
    name: "Co-Funding Partner",
  },
  {
    id: 15,
    name: "Completion",
  },
];

export const InternationalBooksHead = [
  {
    id: 1,
    name: "Sr. No",
  },
  {
    id: 2,
    name: "Book Title",
  },
  {
    id: 3,
    name: "Name of Editor(s)",
  },
  {
    id: 4,
    name: "ISBN",
  },
  {
    id: 5,
    name: "Publisher",
  },
  {
    id: 6,
    name: "Web Link",
  },
  {
    id: 7,
    name: "Country of Publication",
  },
  {
    id: 8,
    name: "Year",
  },
  {
    id: 9,
    name: "No of Editor(s)",
  },
];

export const chaptersPublishedHead = [
  {
    id: 1,
    name: "Sr. No",
  },
  {
    id: 2,
    name: "Chapters Title",
  },
  {
    id: 3,
    name: "Book Title",
  },
  {
    id: 4,
    name: "ISBN",
  },
  {
    id: 5,
    name: "Publisher",
  },
  {
    id: 6,
    name: "Web Link",
  },
  {
    id: 7,
    name: "Country of Publication",
  },
  {
    id: 8,
    name: "Author(s) Name",
  },
  {
    id: 9,
    name: "Year",
  },
  {
    id: 10,
    name: "No of Auth(s)",
  },
];

export const ResearchProjectsHead = [
  {
    id: 1,
    name: "Sr. No",
  },
  {
    id: 2,
    name: "Year",
  },
  {
    id: 3,
    name: "Funding Agency",
  },
  {
    id: 4,
    name: "Research Name",
  },
  {
    id: 5,
    name: "Status",
  },
  {
    id: 6,
    name: "Type",
  },
  {
    id: 7,
    name: "Role",
  },
  {
    id: 8,
    name: "Grant Amount",
  },
  {
    id: 9,
    name: "Title",
  },
  {
    id: 10,
    name: "Start Date",
  },
  {
    id: 11,
    name: "End Date",
  },
  {
    id: 12,
    name: "Total Funding",
  },
  {
    id: 13,
    name: "Collaborating Partner",
  },
  {
    id: 14,
    name: "Co-Funding Partner",
  },
  {
    id: 15,
    name: "Completion",
  },
];

//Form Titles
export const formTitles = [
  "1. Research Publications (Impact Journal / HJRS / HEC Recognized Journals)",
  "2. Book Authored / Edited",
  "3. Research Projects",
  "4. Trainings / Workshops / Seminars / Conferences",
  "5. Thesis / FYP Supervised",
  "6. Policy Advocacy or Case Studies Presented to Government Department",
  "7. Links Established with other HEIs / Corporate Sector / Industry / Community",
  "8. Contract Research Awarded by Industry or Government Organizations",
  "9. Civic Engagement Events / Initiatives on Issues of Public Concern",
  "10. Consultancy Contracts with Industry, Commerce or Government",
  "11. Patents / Trade Marks / Design Patent / Copyrights, etc.",
  "12. Research Products / Process / Prototype (e.g. Architectural designs, Assesment tools, Books, Softwares, Apps, Video Lectures, Arts designs,  etc)",
  "13. Science / Arts Products or any Creative Activity / Exhibitions / Showcasing Events / Industry Linkages / Book Fair Arranged by your Department",
  "14. Agreements Signed for Collaboration with Industry, Government or Community (at National / International Level)",
  "15. National or International Honors or Awards Won",
  "16. Do you provide data to HEC, NGOs or any other organization?",
  "17. Community Work",
  "18. Mentorship Programmes",
  "19. Student Organizations / Associations / Clubs / Alumni Groups",
];

// FACULTIES
export const faculties = [
  {
    id: 1,
    title: "Faculty of Arabic and Islamic Studies",
    href: "faculty-of-arabic-and-social-studies",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    departments: [
      {
        id: 1,
        title: "QURAN AND TAFSEER",
        href: "quran-and-tafseer",
      },
      {
        id: 2,
        title: "ARABIC LANGUAGE & LITERATURE",
        href: "arabic-language-literature",
      },
      {
        id: 3,
        title: "SHARI'AH (ISLAMIC LAW & JURISPRUDENCE)",
        href: "shariah",
      },
      {
        id: 4,
        title: "ISLAMIC THOUGHT, HISTORY AND CULTURE",
        href: "islamic-thought",
      },
      {
        id: 5,
        title: "INTERFAITH STUDIES",
        href: "interfaith-studies",
      },
      {
        id: 6,
        title: "HADITH & HADITH SCIENCES",
        href: "hadith-sciences",
      },
      {
        id: 7,
        title: "SEERAT STUDIES",
        href: "seerat-studies",
      },
    ],
  },
  {
    id: 2,
    title: "Faculty of Education",
    href: "faculty-of-education",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    departments: [
      {
        id: 1,
        title: "EDUCATIONAL PLANNING, POLICY STUDIES AND LEADERSHIP (EPPSL)",
        href: "educational-planning",
      },
      {
        id: 2,
        title: "DISTANCE, NON-FORMAL AND CONTINUING EDUCATION",
        href: "non-formal-and-continuing-education",
      },
      {
        id: 3,
        title: "EARLY CHILDHOOD EDUCATION & ELEMENTARY TEACHER EDUCATION",
        href: "early-childhood-education",
      },
      {
        id: 4,
        title: "SCIENCE EDUCATION",
        href: "science-education",
      },
      {
        id: 5,
        title: "SPECIAL EDUCATION",
        href: "special-education",
      },
      {
        id: 6,
        title: "SECONDARY TEACHER EDUCATION",
        href: "secondary-teacher-education",
      },
      {
        id: 7,
        title: "Center for Social Reconstruction",
        href: "center-for-social-reconstruction",
      },
    ],
  },
  {
    id: 3,
    title: "Faculty of Sciences",
    href: "faculty-of-sciences",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    departments: [
      {
        id: 1,
        title: "CHEMISTRY",
        href: "chemistry",
      },
      {
        id: 2,
        title: "BIOLOGY",
        href: "biology",
      },
      {
        id: 3,
        title: "MATHEMATICS",
        href: "mathematics",
      },
      {
        id: 4,
        title: "COMPUTER SCIENCE",
        href: "computer-science",
      },
      {
        id: 5,
        title: "PHYSICS",
        href: "physics",
      },
      {
        id: 6,
        title: "AGRICULTURAL SCIENCES",
        href: "agricultural-sciences",
      },
      {
        id: 7,
        title: "STATISTICS",
        href: "statistics",
      },
      {
        id: 8,
        title: "ENVIRONMENTAL SCIENCES",
        href: "environmental-sciences",
      },
      {
        id: 9,
        title: "ENGINEERING AND TECHNOLOGY",
        href: "engineering-and-technology",
      },
      {
        id: 10,
        title: "NUTRITIONAL SCIENCES & ENVIRONMENTAL DESIGN",
        href: "nutritional-sciences-and-environmental-design",
      },
    ],
  },
  {
    id: 4,
    title: "Faculty of Social Sciences and Humanities",
    href: "faculty-of-social-sciences-and-humanities",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
    departments: [
      {
        id: 1,
        title: "URDU",
        href: "urdu",
      },
      {
        id: 2,
        title: "COMMERCE",
        href: "commerce",
      },
      {
        id: 3,
        title: "IQBAL STUDIES",
        href: "iqbal-studies",
      },
      {
        id: 4,
        title: "MASS COMMUNICATION",
        href: "mass-communication",
      },
      {
        id: 5,
        title: "LIBRARY AND INFORMATION SCIENCE",
        href: "library-and-information-science",
      },
      {
        id: 6,
        title: "GENDER AND WOMEN STUDIES",
        href: "gender-and-women-studies",
      },
      {
        id: 7,
        title: "PAKISTANI LANGUAGE",
        href: "pakistani-language",
      },
      {
        id: 8,
        title: "ENGLISH",
        href: "english",
      },
      {
        id: 9,
        title: "BUSINESS ADMINISTRATION",
        href: "business-administration",
      },
      {
        id: 10,
        title: "SOCIOLOGY, SOCIAL WORK & POP. STUDIES",
        href: "social-work-and-pop-studies",
      },
      {
        id: 11,
        title: "ECONOMICS",
        href: "economics",
      },
      {
        id: 12,
        title: "FRENCH",
        href: "french",
      },
      {
        id: 13,
        title: "HISTORY",
        href: "history",
      },
      {
        id: 14,
        title: "PAKISTAN STUDIES",
        href: "pakistan-studies",
      },
    ],
  },
];

// NAVLINKS
export const navLinks = [
  { id: 1, title: "Home", href: "/" },
  { id: 2, title: "About ORIC", href: "/about" },
  { id: 3, title: "Contact", href: "/contact" },
];

export const nameTitles = [
  { title: "Dr" },
  { title: "Mr" },
  { title: "Ms" },
  { title: "Mrs" },
];
